### PR TITLE
Convert to PHP 5.4+ short array syntax

### PR DESCRIPTION
**Pull request by kghbln**

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames Currently this extension is still on PHP 5.3+ and MW 1.23+ so this is breaking. If ok I will do a follow-up PR to update the READMEs

**Comment by JeroenDeDauw** [comment]
+1

**Comment by mwjames** [comment]
Feel free to merge (given that tests have passed). We should also make
sure min requirements are PHP 5.5 and MW 1.27.

- composer.json -> PHP 5.5
- .travis.yaml uses REL1_27 for all jobs < 1.27

**Comment by kghbln** [comment]
https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/pull/34

**Pull request merged**
