### PR TITLE
Fix warning in PHP > 7.1

### PR DESCRIPTION
**Pull request by jaideraf**
Fix Warning: Use of undefined constant ... - assumed '...'.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Did you encounter this error after upgrading to 2.0?

**Comment by jaideraf** [comment]
Oh, now I just saw https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/issues/56 and it is a duplication of this one.
@JeroenDeDauw I got these warnings after upgrading from PHP 7.1 to 7.2 (yes, using SBL 2.0).
I didn't know my proposed change to a `.md` file would introduce a bug. After I changed these `NAMES` by `'NAMES'` the warnings disapeard and I thought I was improving just a documentation page.

**Comment by JeroenDeDauw** [comment]
I did not notice this was in an .md file. Either way, the change is incorrect and I do not advise you to apply it in your PHP code.

**Comment by JeroenDeDauw** [comment]
I explained the cause of the error at  #56

**Pull request closed without merging**
